### ISSUE TITLE
Возможно опечатка в статье "Готовим селекторы"

### ISSUE THREAD

**Issue by GTech1256** [risenforces/risen.dev#3]
В тексте есть предложение 

> Такой подход конечно же неправильный, и мемоизированные селекторы не всегда.

И не понятно что предполагается под `и мемоизированные селекторы не всегда.`

[Ссылка на абзац](https://github.com/risenforces/risen.dev/blob/master/content/blog/cooking-selectors/index.md#%D0%BC%D0%B5%D0%BC%D0%BE%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-memoized-selectors)

**Comment by risenxxx** [comment]
Спасибо, поправил
